# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Complex Systems Winter School
email: complexsystemsturkey@gmail.com
description: >
  This website is under construction. It is cloned from hillhacks.in
keywords: >
  dynamical systems, chaos, complex systems, school, 
baseurl: ""
github_username: "complex-systems-turkey"
schedule: https://osem.hillhacks.in/conferences/hillhacks2017/schedule

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
collections:
  sessions:
    output: false
  dates:
    output: false